version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./pages:/app/pages
    user: "1000:1000"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./nginx/certbot.conf:/etc/nginx/conf.d/certbot.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:rw

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - nginx
